.github/workflows/publish-installer-pre-release.yml, .github/workflows/publish-installer-release-and-repackage.yml, .github/workflows/publish-pre-release.yml, .github/workflows/publish-release.yml
@jasonh-edfi @jagudelo-gap 
Please help review and merge the changes.
Thanks
=> [DI-1270] Update PAT name on GH workflows

DataImport.E2E.Tests/features/management/teardown.ts, DataImport.E2E.Tests/features/models/configurationPage.ts, DataImport.E2E.Tests/features/models/dataImportPage.ts, DataImport.E2E.Tests/features/models/exportTemplatePage.ts, DataImport.E2E.Tests/features/models/importExportPage.ts, DataImport.E2E.Tests/features/models/loginPage.ts, DataImport.E2E.Tests/features/support/configuration.ts, DataImport.E2E.Tests/features/support/export.ts, DataImport.E2E.Tests/features/support/import.ts, DataImport.E2E.Tests/features/support/login.ts
Updating and solving the execution of E2E from Data Import. 
@CSR2017 @jasonh-edfi  could you review the changes?
=> Fix E2E test Execution

build.ps1
@jpardogrowthaccelerationpartners
=> [DI-1008] Fix build error

.github/workflows/on-prerelease.yml, DataImport.Web/DataImport.Web.csproj, DataImport.Web/DataImport.Web.nuspec, Installer/Install-EdFiDataImport.psm1, Installer/install.ps1, build.ps1, docs/build-script.md, eng/package-manager.psm1
@jagudelo-gap @jasonh-edfi 
Please help review and merge the changes,
Thanks
=> [DI-1281] Combine Data Import web package and installer

Compose/pgsql/.env.example, Compose/pgsql/compose-build.yml, Dockerfile
@jasonh-edfi @jpardogrowthaccelerationpartners 
Please help review and merge the changes.
Thanks
=> [DI-115] and [DI-1180] Update Dockerfile Data Import to accommodate new structure change

DataImport.Server.TransformLoad/Features/LoadResources/FileProcessor.cs
@CSR2017 @lchavarriaga 
Please help review and merge the changes.
Thanks
=> [DI-1249] - Row number error

.github/workflows/on-prerelease.yml, .github/workflows/on-pullrequest-or-push.yml, .github/workflows/on-pullrequest.yml, DataImport.EdFi.UnitTests/DataImport.EdFi.UnitTests.csproj, DataImport.Web/Features/UserReset/RecoverUserController.cs
@jagudelo-gap @jpardogrowthaccelerationpartners 
Please help review and merge the changes.
Thanks
=> [DI-1288] Recovered user enable lockout

.github/workflows/on-pullrequest-or-push.yml
@jpardogrowthaccelerationpartners
=> [DI-1288] check for pull-request action for dependency review run

DataImport.Server.TransformLoad/Features/LoadResources/FileProcessor.cs, DataImport.Server.TransformLoad/Features/LoadResources/PostBootstrapData.cs
@jpardogrowthaccelerationpartners @jasonh-edfi 
The changes are safe. I tested it on my docker. Testing them in local dev environment.
Thanks
=> [DI-1288] Fix for missing bootstrap id and log details on the error case

Dockerfile, Installer/install.ps1
@jpardogrowthaccelerationpartners
=> [DI-1288] Update version on docker file and install.ps1 file

.github/workflows/on-pullrequest-or-push.yml, build.ps1
Fix publish for build.ps1
Update workflow condition
=> [DI-1337] NET 8 - Actions update

DataImport.Common.Tests/DataImport.Common.Tests.csproj, DataImport.Common/DataImport.Common.csproj, DataImport.EdFi.UnitTests/DataImport.EdFi.UnitTests.csproj, DataImport.EdFi/DataImport.EdFi.csproj, DataImport.Server.TransformLoad.Tests/DataImport.Server.TransformLoad.Tests.csproj, DataImport.Server.TransformLoad/DataImport.Server.TransformLoad.csproj, DataImport.Web.Tests/DataImport.Web.Tests.csproj, DataImport.Web/DataImport.Web.csproj
Add direct reference to libuv package to use latest version.
=>  [DI-1346] Data Import 2.3 .NET 8 Update - Remove warnings

Compose/pgsql/compose-build.yml, DataImport.Web/Helpers/JsonValidator.cs, dev.Dockerfile
- Remove platform and image
- Update port 80 to listen 8080
=> [DI-1359] Fix .yml file to raise DataImport in Docker

DataImport.Common/AzureFileService.cs, DataImport.Common/DataImport.Common.csproj
- Remove deprecated package WindowsAzure.Storage
- Add package Azure.Storage.Files.Shares
- Update code to replace types, objects and methods to use the new package
=> [DI-1356] Data Import 2.3 .NET 8 Update - Deprecated Packages: WindowsAzure.Storage

docs/build-script.md, docs/powershell-installation.md
Update documentaion to use references to NET 8 instead of NET 6.
=> [DI-1357]  Update readme files with .NET 8 and new tech docs links

DataImport.Server.TransformLoad/Features/LoadResources/FileProcessor.cs
Update log message when the file doesn't exist
=> [DI-1314] Data import executable failed looking for a specific directory in the local users temp folder

DataImport.Common/DataImport.Common.csproj, DataImport.Web.Tests/Features/ApiServers/RefreshDataModelTests.cs, DataImport.Web.Tests/Testing.cs, DataImport.Web/Features/ApiServers/ApiServersController.cs, DataImport.Web/Features/ApiServers/Index.cshtml, DataImport.Web/Features/ApiServers/RefreshDataModel.cs
Adding a new button to refresh DataMaps and Resources tables
Authored by @beto-devnet
=> [DI-1307] Staging - Adding DataModel refresh option  (#100)

DataImport.Web/Features/Agent/_PartialAgentForm.cshtml
Remove style to fix table render.
=> [DI-1369] UI Fix: The columns in 'Data Map' are not shown with the correct distribution, everything is together

DataImport.Common/LocalFileService.cs, DataImport.Server.TransformLoad.Tests/Features/FileTransport/TestFileServer.cs, DataImport.Server.TransformLoad/Application.cs, DataImport.Server.TransformLoad/Features/FileTransport/FileServer.cs, DataImport.Server.TransformLoad/Features/FileTransport/FileTransporter.cs, DataImport.Server.TransformLoad/Features/Helper.cs, DataImport.Server.TransformLoad/Features/LoadResources/FileProcessor.cs, DataImport.Web/Features/Shared/_Layout.cshtml
Updata workflow to delete files from the dataimport folder. Files are removed from the data import folder, and they are not removed from the FTP Server (external source)
=> [DI-1370]  After running the transformLoad delete the files on the DataImport folder with action (Always Delete)

Dockerfile, Installer/install.ps1
* Update package version used by installer
* Update package version used by dockerfile
=> [DI-1368] Update package version for 2.3 release

DataImport.Common.Tests/DataImport.Common.Tests.csproj, DataImport.Common/DataImport.Common.csproj, DataImport.EdFi.UnitTests/DataImport.EdFi.UnitTests.csproj, DataImport.Models.Tests/DataImport.Models.Tests.csproj, DataImport.Models/DataImport.Models.csproj, DataImport.Server.TransformLoad.Tests/DataImport.Server.TransformLoad.Tests.csproj, DataImport.Server.TransformLoad/DataImport.Server.TransformLoad.csproj, DataImport.Web.Tests/DataImport.Web.Tests.csproj, DataImport.Web/DataImport.Web.csproj, eng/promote-packages.psm1
- Update substring index.
- Update nuget version to fix vulnerabilities
=> [DI-1388] Fix package name format for package promotion in azure 'on-release.yml
